# Generated by Django 4.2.5 on 2024-01-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_event_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
