# Generated by Django 4.2.5 on 2024-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeEnd',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timeStart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dataEnd',
            field=models.DateField(null=True),
        ),
    ]
