# Generated by Django 4.2.5 on 2024-01-12 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0006_rename_event_eventactual_eventhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventHistory',
            new_name='EventHistorys',
        ),
    ]
