# Generated by Django 4.2.5 on 2024-01-12 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0007_rename_eventhistory_eventhistorys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventActual',
            new_name='HistoryEvent',
        ),
    ]
