# Generated by Django 4.2.5 on 2024-01-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0009_rename_eventhistorys_actualevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='actualevent',
            name='user_reporting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualevent',
            name='user_solving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solved_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
