# Generated by Django 4.2.8 on 2023-12-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terminale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('terminal', models.CharField(max_length=16)),
                ('stan', models.BinaryField()),
            ],
        ),
    ]
