# Generated by Django 4.2.8 on 2023-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Terminale', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='stan',
            field=models.CharField(max_length=8),
        ),
    ]
